#all var are stored in plain text
apiVersion: v1
kind: ConfigMap
metadata:
  name: vars-config
data:
  DATABASE_URL: "postgresql://drkiq:yourpassword@postgres:5432/drkiq?encoding=utf8&pool=5&timeout=5000"
  POSTGRES_USER: "drkiq"
  POSTGRES_PASSWORD: "yourpassword"
  CACHE_URL: "redis://redis:6379/0"
  JOB_WORKER_URL: "redis://redis:6379/0"
  WORKER_PROCESSES: "1"
  LISTEN_ON: "0.0.0.0:8000"
  SECRET_TOKEN: "8d428e9d27e3323f1b1ec0089482017480224c9984fc10327f95b0990ec46175d43d756fd644c3bca3703a337a94ced69c868ab0470ac201cd1b6a80c3f89e4a"
