---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: drkiq-pv
  labels:
    app: drkiq
spec:
  storageClassName: manual
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/drkiq"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres 
  name: drkiq-claim
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
