## this volume used for store database data in exrnal path out container
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  labels:
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/postgres-pv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres 
  name: postgres-claim
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
