apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: postgres
  type: ClusterIP
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:9.4.5

## two vars for database configuration
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: secret-app
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-app
              key: POSTGRES_PASSWORD
## communication port with other app
        ports:
        - containerPort: 5432
          name: postgres

## attached volume to store database
        volumeMounts:
        - name : pg-volume
          mountPath : /var/lib/postgresql/data/

      volumes:
      - name: pg-volume
        persistentVolumeClaim:
          claimName: postgres-claim
