## this volume for store redis data in externl path out of container
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv
  labels:
    app: redis
spec:
  storageClassName: manual
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/redis-pv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: redis
  name: redis-claim
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 30Gi

