## all these secret is used in deployment and convert them to base64 for security
apiVersion: v1
kind: Secret
metadata:
  name: secret-app
data:
  CACHE_URL: cmVkaXM6Ly9yZWRpczo2Mzc5LzA=
  DATABASE_URL: cG9zdGdyZXNxbDovL2Rya2lxOnlvdXJwYXNzd29yZEBwb3N0Z3Jlczo1NDMyL2Rya2lxP2VuY29kaW5nPXV0ZjgmcG9vbD01JnRpbWVvdXQ9NTAwMA==
  JOB_WORKER_URL: cmVkaXM6Ly9yZWRpczo2Mzc5LzA=
  LISTEN_ON: MC4wLjAuMDo4MDAw
  POSTGRES_PASSWORD: eW91cnBhc3N3b3Jk
  POSTGRES_USER: ZHJraXE=
  WORKER_PROCESSES: MQ==
  SECRET_TOKEN: OGQ0MjhlOWQyN2UzMzIzZjFiMWVjMDA4OTQ4MjAxNzQ4MDIyNGM5OTg0ZmMxMDMyN2Y5NWIwOTkwZWM0Ng==

