apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq
spec:
  selector:
    matchLabels:
      app: sidekiq
  template:
    metadata:
      labels:
        app: sidekiq
    spec:
      containers:
      - name: sidekiq
        image: app
        imagePullPolicy: Never
        args: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
        
        ## all these var used for run this container
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: secret-app
              key: DATABASE_URL
        - name: SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: secret-app
              key: SECRET_TOKEN
        - name: WORKER_PROCESSES
          valueFrom:
            secretKeyRef:
              name: secret-app
              key: WORKER_PROCESSES
        - name: LISTEN_ON
          valueFrom:
            secretKeyRef:
              name: secret-app
              key: LISTEN_ON
        - name: CACHE_URL
          valueFrom:
            secretKeyRef:
              name: secret-app
              key: CACHE_URL
        - name: JOB_WORKER_URL
          valueFrom:
            secretKeyRef:
              name: secret-app
              key: JOB_WORKER_URL